[project]
name = "ansible-role-initialuser"
version = "0.1.0"
description = "Sets up the Ansible control user on a Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.2.0",
    "ansible-lint>=25.1.3",
    "molecule-docker>=2.1.0",
]
